version: '3.8'

services:
  cassandra:
    image: cassandra:4.0.3
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=akka-cassandra-cluster
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: lite-keep
      POSTGRES_PASSWORD: lite-keep

